-- MySQL Script generated by MySQL Workbench
-- Thu Sep 14 00:30:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD_seguridad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_seguridad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_seguridad` DEFAULT CHARACTER SET utf8 ;
USE `BD_seguridad` ;

-- -----------------------------------------------------
-- Table `BD_seguridad`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_seguridad`.`Perfil` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `nombre_perfil` VARCHAR(50) NOT NULL,
  `descripcion_perfil` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_seguridad`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_seguridad`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `apellido_usuario` VARCHAR(50) NOT NULL,
  `id_perfil` INT NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `correo_usuario` VARCHAR(45) NULL,
  `telefono_usuario` INT(8) NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `FK_usuario_perfil_idx` (`id_perfil` ASC),
  CONSTRAINT `FK_usuario_perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `BD_seguridad`.`Perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_seguridad`.`Aplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_seguridad`.`Aplicacion` (
  `id_aplicacion` INT NOT NULL AUTO_INCREMENT,
  `nombre_aplicacion` VARCHAR(50) NOT NULL,
  `descripcion_aplicacion` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_aplicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_seguridad`.`Detalle_perfil_aplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_seguridad`.`Detalle_perfil_aplicacion` (
  `id_perfil` INT NOT NULL,
  `id_aplicacion` INT NOT NULL,
  PRIMARY KEY (`id_perfil`, `id_aplicacion`),
  INDEX `FK_detalle_aplicacion_idx` (`id_aplicacion` ASC),
  CONSTRAINT `FK_detalle_perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `BD_seguridad`.`Perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_detalle_aplicacion`
    FOREIGN KEY (`id_aplicacion`)
    REFERENCES `BD_seguridad`.`Aplicacion` (`id_aplicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_seguridad`.`Derecho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_seguridad`.`Derecho` (
  `id_derecho` INT NOT NULL AUTO_INCREMENT,
  `nombre_derecho` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_derecho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_seguridad`.`Detalle_aplicacion_derecho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_seguridad`.`Detalle_aplicacion_derecho` (
  `id_aplicacion` INT NOT NULL,
  `id_derecho` INT NOT NULL,
  PRIMARY KEY (`id_aplicacion`, `id_derecho`),
  INDEX `FK_detalle_derecho_idx` (`id_derecho` ASC),
  CONSTRAINT `FK_detalle_aplicacion2`
    FOREIGN KEY (`id_aplicacion`)
    REFERENCES `BD_seguridad`.`Aplicacion` (`id_aplicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_detalle_derecho`
    FOREIGN KEY (`id_derecho`)
    REFERENCES `BD_seguridad`.`Derecho` (`id_derecho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_seguridad`.`Bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_seguridad`.`Bitacora` (
  `id_bitacora` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `fecha_bitacora` DATE NOT NULL,
  `hora_bitacora` TIME(6) NOT NULL,
  `accion_usuario` VARCHAR(45) NOT NULL,
  `tabla` VARCHAR(45) NOT NULL,
  `resultado_bitacora` VARCHAR(45) NOT NULL,
  `error_bitacora` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id_bitacora`),
  INDEX `FK_bitacora_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `FK_bitacora_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `BD_seguridad`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_seguridad`.`Cambio_Contraseña`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_seguridad`.`Cambio_Contraseña` (
  `id_cambio` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `contraseña_actual` VARCHAR(45) NOT NULL,
  `contraseña_nueva` VARCHAR(45) NOT NULL,
  `fecha_cambio` DATE NOT NULL,
  PRIMARY KEY (`id_cambio`),
  INDEX `FK_cambio_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `FK_cambio_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `BD_seguridad`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into derecho (nombre_derecho) values ('Insertar');
insert into derecho (nombre_derecho) values ('Eliminar');
insert into derecho (nombre_derecho) values ('Modificar');

alter table usuario change contraseña contrasena varchar(45);
